### ISSUE TITLE
Not Found.

### ISSUE THREAD

**Issue by datomnurdin** [amree/teecket-web#3]
I think it's more better if you set a proper not found message.

![screen shot 2015-06-16 at 11 36 26 am](https://cloud.githubusercontent.com/assets/5416242/8175320/649b4db0-141b-11e5-9f52-952518f6bd10.png)

**Comment by amree** [comment]
Yeah, this is actually in my todo list. Thanks for reporting it. Going to
open this one untill there's a pull request for it (from me or anyone)
